[workspace]
authors = ["mattbocc <matthew.boccalon@live.ca>"]
channels = ["conda-forge"]
name = "clinical-trial-scraper"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.7,<3.14"
pyvirtualdisplay = ">=2.2,<3"
unidecode = ">=1.3.8,<2"
pandas = ">=2.3.2,<3"
python-dotenv = ">=1.1.1,<2"

[pypi-dependencies]
nodriver = ">=0.47.0, <0.48"
